<a href="https://colab.research.google.com/github/chirantansaha-22/NLP-WordEmbeddings/blob/main/Word_Embedding_in_DL_using_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install tensorflow

In [4]:
import tensorflow as tf

In [5]:
tf.__version__

'2.15.0'

In [6]:
from tensorflow.keras.preprocessing.text import one_hot

In [12]:
paragraph=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [13]:
paragraph

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [14]:
vocab_size=500

In [15]:
ohe_encoded=[one_hot(sentence,vocab_size) for sentence in paragraph]

In [16]:
ohe_encoded

[[369, 51, 209, 286],
 [369, 51, 209, 340],
 [369, 491, 209, 156],
 [131, 201, 38, 208, 223],
 [131, 201, 38, 208, 268],
 [459, 369, 92, 209, 103],
 [297, 400, 82, 208]]

In [17]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [30]:
sent_length=8
padded_ohe=pad_sequences(ohe_encoded,padding="pre",maxlen=sent_length)
padded_ohe

array([[  0,   0,   0,   0, 369,  51, 209, 286],
       [  0,   0,   0,   0, 369,  51, 209, 340],
       [  0,   0,   0,   0, 369, 491, 209, 156],
       [  0,   0,   0, 131, 201,  38, 208, 223],
       [  0,   0,   0, 131, 201,  38, 208, 268],
       [  0,   0,   0, 459, 369,  92, 209, 103],
       [  0,   0,   0,   0, 297, 400,  82, 208]], dtype=int32)

In [29]:
#tf.keras.backend.clear_session()

In [31]:
model=Sequential()

In [32]:
model.add(Embedding(vocab_size,25,input_length=sent_length))
model.compile(optimizer='adam',loss='mse')

In [33]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 25)             12500     
                                                                 
Total params: 12500 (48.83 KB)
Trainable params: 12500 (48.83 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [34]:
padded_ohe[0]

array([  0,   0,   0,   0, 369,  51, 209, 286], dtype=int32)

In [35]:
output_padded_0=model.predict(padded_ohe[0])

1/1 [==============================] - 0s 37ms/step


In [36]:
output_padded_0.shape

(8, 25)

In [37]:
model.predict(padded_ohe)

1/1 [==============================] - 0s 34ms/step


array([[[-0.01015759,  0.02418194, -0.04891051, ...,  0.03608869,
         -0.00280112,  0.01486415],
        [-0.01015759,  0.02418194, -0.04891051, ...,  0.03608869,
         -0.00280112,  0.01486415],
        [-0.01015759,  0.02418194, -0.04891051, ...,  0.03608869,
         -0.00280112,  0.01486415],
        ...,
        [ 0.02161056, -0.03415811,  0.03852335, ...,  0.0227936 ,
          0.0213164 ,  0.04258763],
        [ 0.00926441, -0.00982281,  0.00466546, ...,  0.01635695,
          0.01711817, -0.02178252],
        [ 0.01232457,  0.04587734,  0.0498617 , ...,  0.03174592,
         -0.01426836,  0.01476489]],

       [[-0.01015759,  0.02418194, -0.04891051, ...,  0.03608869,
         -0.00280112,  0.01486415],
        [-0.01015759,  0.02418194, -0.04891051, ...,  0.03608869,
         -0.00280112,  0.01486415],
        [-0.01015759,  0.02418194, -0.04891051, ...,  0.03608869,
         -0.00280112,  0.01486415],
        ...,
        [ 0.02161056, -0.03415811,  0.03852335, ...,  